### ISSUE TITLE
Remove files from hidden list

### ISSUE THREAD

**Issue by Ocelot08** [kelszo/obsidian-file-explorer-plus#9]
### What would you like to be added?

I don't see a way to remove a file from the hidden list once it has been added. am I missing something here?

### Why is this needed?

If I mistakenly hide a folder, I currently need to uninstall and then reinstall the plugin to reset all hidden folders

**Comment by kelszo** [comment]
![image](https://github.com/kelszo/obsidian-file-explorer-plus/assets/41587072/3ac10400-58a3-4bf8-9b78-81733c436e48)


You need to disable the "Hide strict path filters in settings" setting. The setting exists so that the strict filters do not clutter the settings panel as they accumulate. You should now be able to see all the folders you have hidden using the right click menu.

**Comment by Ocelot08** [comment]
Resolved, thank you!
